import type { Metadata } from "next";
import { cookies } from "next/headers";
import SideBar from "./components/sidebar";

import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Admin Area",
  description: "Generated by create next app",
  robots: "none",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get("logged_in");
  return (
    <>
      {theme?.value === process.env.ADMIN_TOKEN ? (
        <main className={styles.mainArea}>
          <SideBar />
          {children}
        </main>
      ) : (
        <div>"You are not Admin"</div>
      )}
    </>
  );
}
