import type { Metadata } from "next";
import { cookies } from "next/headers";

import AdminDrawer from "./components/drawer/adminDrawer";
import LoginForm from "../login/components/LoginForm";

import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Admin Area",
  description: "Generated by create next app",
  robots: "none",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const loggedInToken = cookieStore.get("logged_in");

  return (
    <>
      {!loggedInToken ? (
        <LoginForm />
      ) : loggedInToken?.value === process.env.ADMIN_TOKEN ? (
        <>
          <main className={styles.mainArea}>
            <AdminDrawer />
            {children}
          </main>
        </>
      ) : (
        <div>"You are not Admin. Access Prohibited!"</div>
      )}
    </>
  );
}
